/*
 * Copyright 2017 Pablo Barrientos (pablo.barrientos@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.funky.curry

/*
 * Extensions to convert a function with [2 to 22] parameters to a curried function.
 */
fun <A, B, Z> ((A, B) -> Z).curried(): (A) -> (B) -> Z = { p1: A -> { p2: B -> this(p1, p2) } }
fun <A, B, C, Z> ((A, B, C) -> Z).curried(): (A) -> (B) -> (C) -> Z = { p1: A -> { p2: B -> { p3: C -> this(p1, p2, p3) } } }
fun <A, B, C, D, Z> ((A, B, C, D) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> this(p1, p2, p3, p4) } } } }
fun <A, B, C, D, E, Z> ((A, B, C, D, E) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> this(p1, p2, p3, p4, p5) } } } } }
fun <A, B, C, D, E, F, Z> ((A, B, C, D, E, F) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> this(p1, p2, p3, p4, p5, p6) } } } } } }
fun <A, B, C, D, E, F, G, Z> ((A, B, C, D, E, F, G) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> this(p1, p2, p3, p4, p5, p6, p7) } } } } } } }
fun <A, B, C, D, E, F, G, H, Z> ((A, B, C, D, E, F, G, H) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> this(p1, p2, p3, p4, p5, p6, p7, p8) } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, Z> ((A, B, C, D, E, F, G, H, I) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9) } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, Z> ((A, B, C, D, E, F, G, H, I, J) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, Z> ((A, B, C, D, E, F, G, H, I, J, K) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, Z> ((A, B, C, D, E, F, G, H, I, J, K, L) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12) } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13) } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14) } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15) } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16) } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17) } } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> { p18: R -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18) } } } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> { p18: R -> { p19: S -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19) } } } } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> { p18: R -> { p19: S -> { p20: T -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20) } } } } } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> { p18: R -> { p19: S -> { p20: T -> { p21: U -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21) } } } } } } } } } } } } } } } } } } } } }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, Z> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) -> Z).curried(): (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> Z = { p1: A -> { p2: B -> { p3: C -> { p4: D -> { p5: E -> { p6: F -> { p7: G -> { p8: H -> { p9: I -> { p10: J -> { p11: K -> { p12: L -> { p13: M -> { p14: N -> { p15: O -> { p16: P -> { p17: Q -> { p18: R -> { p19: S -> { p20: T -> { p21: U -> { p22: V -> this(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22) } } } } } } } } } } } } } } } } } } } } } }

/*
 * Extensions to convert a curried function to an uncurried function.
 */
fun <A, B, Z> ((A) -> (B) -> Z).uncurried(): (A, B) -> Z = { p1: A, p2: B -> this(p1)(p2) }
fun <A, B, C, Z> ((A) -> (B) -> (C) -> Z).uncurried(): (A, B, C) -> Z = { p1: A, p2: B, p3: C -> this(p1)(p2)(p3) }
fun <A, B, C, D, Z> ((A) -> (B) -> (C) -> (D) -> Z).uncurried(): (A, B, C, D) -> Z = { p1: A, p2: B, p3: C, p4: D -> this(p1)(p2)(p3)(p4) }
fun <A, B, C, D, E, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> Z).uncurried(): (A, B, C, D, E) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E -> this(p1)(p2)(p3)(p4)(p5) }
fun <A, B, C, D, E, F, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> Z).uncurried(): (A, B, C, D, E, F) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F -> this(p1)(p2)(p3)(p4)(p5)(p6) }
fun <A, B, C, D, E, F, G, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> Z).uncurried(): (A, B, C, D, E, F, G) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7) }
fun <A, B, C, D, E, F, G, H, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> Z).uncurried(): (A, B, C, D, E, F, G, H) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8) }
fun <A, B, C, D, E, F, G, H, I, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9) }
fun <A, B, C, D, E, F, G, H, I, J, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10) }
fun <A, B, C, D, E, F, G, H, I, J, K, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q, p18: R -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q, p18: R, p19: S -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q, p18: R, p19: S, p20: T -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q, p18: R, p19: S, p20: T, p21: U -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21) }
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, Z> ((A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> (K) -> (L) -> (M) -> (N) -> (O) -> (P) -> (Q) -> (R) -> (S) -> (T) -> (U) -> (V) -> Z).uncurried(): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) -> Z = { p1: A, p2: B, p3: C, p4: D, p5: E, p6: F, p7: G, p8: H, p9: I, p10: J, p11: K, p12: L, p13: M, p14: N, p15: O, p16: P, p17: Q, p18: R, p19: S, p20: T, p21: U, p22: V -> this(p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22) }